include-and-override=portal-developer.properties
theme.css.fast.load=false
theme.images.fast.load=false
javascript.fast.load=false
layout.template.cache.enabled=false
freemarker.engine.resource.modification.check.interval=0
browser.launcher.url=

#
# MySQL
#
#jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
#jdbc.default.url=jdbc:mysql://dev.server/lportaldev
#jdbc.default.username=root
#jdbc.default.password=