##
## Check GETTING_STARTED.md for additional properties and their default values.
##

liferay.workspace.bundle.dist.include.metadata=true
liferay.workspace.modules.dir=modules
liferay.workspace.themes.dir=themes
liferay.workspace.wars.dir=modules
microsoft.translator.subscription.key=
liferay.workspace.product=dxp-2026.q1.0-lts
target.platform.version=2026.q1.0
liferay.workspace.target.platform.index.sources=true
# Entorno por defecto del workspace
liferay.workspace.environment=dev
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8